services:
  postgresdb:
    image: postgres
    restart: always
    ports:
      - 8087:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: test

  authentication-service:
    build: 
      context: ./authentication-service
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: root
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgresdb
      POSTGRES_PASSWORD: example
      POSTGRES_DB: test
    command: uvicorn service:app --host=0.0.0.0 --port=8081 --reload
    ports:
      - 8081:8081
    depends_on:
      - postgresdb
    volumes:
      - ./authentication-service:/app
  # businesses-service:
  # design-service:
  # developers-service:
  # portfolio-service:
  # resume-service:
  api-service:
    build: 
      context: ./api-service
      dockerfile: Dockerfile
    command: uvicorn service:app --host=0.0.0.0 --port=8080 --reload
    ports:
      - 8080:8080
    depends_on:
      - authentication-service
    volumes:
      - ./api-service:/app
      
