services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 8087:8087
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  authentication-service:
    build: 
      context: ./authentication-service
      dockerfile: Dockerfile
    environment:
      - MONGODB_URL=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=admin
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=example
    command: uvicorn service:app --host=0.0.0.0 --port=8081 --reload
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    volumes:
      - ./authentication-service:/app
  # businesses-service:
  # design-service:
  # developers-service:
  # portfolio-service:
  # resume-service:
  api-service:
    build: 
      context: ./api-service
      dockerfile: Dockerfile
    command: uvicorn service:app --host=0.0.0.0 --port=8080 --reload
    ports:
      - 8080:8080
    depends_on:
      - authentication-service
    volumes:
      - ./api-service:/app

